package cn.ffcs.uom.webservices.bean.network;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 03:52:48 ���� CST 
//



import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.ffcs.vo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.ffcs.vo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root.Data }
     * 
     */
    public Root.Data createRootData() {
        return new Root.Data();
    }

    /**
     * Create an instance of {@link Root.Data.BasicInfo }
     * 
     */
    public Root.Data.BasicInfo createRootDataBasicInfo() {
        return new Root.Data.BasicInfo();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

}
