package cn.ffcs.uom.webservices.bean.network;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.03 at 03:52:48 ���� CST 
//



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="basicInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="the_orgname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="thehigh_orgname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="if_occupy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="network_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected Root.Data data;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Root.Data }
     *     
     */
    public Root.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Root.Data }
     *     
     */
    public void setData(Root.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="basicInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="the_orgname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="thehigh_orgname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="if_occupy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="network_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "basicInfo"
    })
    public static class Data {

        @XmlElement(required = true)
        protected Root.Data.BasicInfo basicInfo;

        /**
         * Gets the value of the basicInfo property.
         * 
         * @return
         *     possible object is
         *     {@link Root.Data.BasicInfo }
         *     
         */
        public Root.Data.BasicInfo getBasicInfo() {
            return basicInfo;
        }

        /**
         * Sets the value of the basicInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Root.Data.BasicInfo }
         *     
         */
        public void setBasicInfo(Root.Data.BasicInfo value) {
            this.basicInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="serial" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="the_orgname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="thehigh_orgname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="if_occupy" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="network_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class BasicInfo {

            @XmlElement(required = true)
            protected String instance;
            @XmlElement(required = true)
            protected String serial;
            @XmlElement(name = "the_orgname", required = true)
            protected String theOrgname;
            @XmlElement(name = "thehigh_orgname", required = true)
            protected String thehighOrgname;
            @XmlElement(required = true)
            protected String action;
            @XmlElement(name = "if_occupy", required = true)
            protected String ifOccupy;
            @XmlElement(name = "network_code")
            protected String networkCode;

            /**
             * Gets the value of the instance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInstance() {
                return instance;
            }

            /**
             * Sets the value of the instance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInstance(String value) {
                this.instance = value;
            }

            /**
             * Gets the value of the serial property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerial() {
                return serial;
            }

            /**
             * Sets the value of the serial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerial(String value) {
                this.serial = value;
            }

            /**
             * Gets the value of the theOrgname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTheOrgname() {
                return theOrgname;
            }

            /**
             * Sets the value of the theOrgname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTheOrgname(String value) {
                this.theOrgname = value;
            }

            /**
             * Gets the value of the thehighOrgname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getThehighOrgname() {
                return thehighOrgname;
            }

            /**
             * Sets the value of the thehighOrgname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setThehighOrgname(String value) {
                this.thehighOrgname = value;
            }

            /**
             * Gets the value of the action property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAction() {
                return action;
            }

            /**
             * Sets the value of the action property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAction(String value) {
                this.action = value;
            }

            /**
             * Gets the value of the ifOccupy property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIfOccupy() {
                return ifOccupy;
            }

            /**
             * Sets the value of the ifOccupy property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIfOccupy(String value) {
                this.ifOccupy = value;
            }

            /**
             * Gets the value of the networkCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNetworkCode() {
                return networkCode;
            }

            /**
             * Sets the value of the networkCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNetworkCode(String value) {
                this.networkCode = value;
            }

        }

    }

}
