package cn.ffcs.uom.organization.model;

// Generated 2017-6-27 16:42:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import cn.ffcs.uom.common.dao.BaseDao;
import cn.ffcs.uom.common.util.ApplicationContextUtil;

/**
 * HanaWbCorpId generated by hbm2java
 */
public class HanaWbCorp implements java.io.Serializable {
	private static final long serialVersionUID = 1150051246085225289L;
	
	private int monthId;
	private String unitId;
	private String pkCorp;
	private String unitcode;
	private String unitname;
	private String legalbodycode;
	private String taxcode;
	private String busilicense;
	private String region;
	private String saleaddr;
	private BigDecimal regcapital;
	private String corptype;
	private String busiscope;
	private String defStr1;
	private String defStr2;
	private String defStr3;
	private String defStr4;
	private String defStr5;
	private String defStr6;
	private String defStr7;
	private String defStr8;
	private BigDecimal defNum1;
	private BigDecimal defNum2;
	private String pkOrg;
	private String pkGroup;
	private String ts;
	private Long dr;

	/**
	 * 构造方法
	 */
	public HanaWbCorp() {
		super();
	}

	/**
	 * 创建对象实例.
	 * 
	 * @return HanaTelSyncCostcenter
	 */
	public static HanaWbCorp newInstance() {
		return new HanaWbCorp();
	}

	/**
	 * 获取dao
	 * 
	 * @return
	 */
	public static BaseDao repository() {
		return (BaseDao) ApplicationContextUtil.getBean("baseDao");
	}

	public int getMonthId() {
		return this.monthId;
	}

	public void setMonthId(int monthId) {
		this.monthId = monthId;
	}

	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	public String getUnitcode() {
		return this.unitcode;
	}

	public void setUnitcode(String unitcode) {
		this.unitcode = unitcode;
	}

	public String getUnitname() {
		return this.unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	public String getLegalbodycode() {
		return this.legalbodycode;
	}

	public void setLegalbodycode(String legalbodycode) {
		this.legalbodycode = legalbodycode;
	}

	public String getTaxcode() {
		return this.taxcode;
	}

	public void setTaxcode(String taxcode) {
		this.taxcode = taxcode;
	}

	public String getBusilicense() {
		return this.busilicense;
	}

	public void setBusilicense(String busilicense) {
		this.busilicense = busilicense;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getSaleaddr() {
		return this.saleaddr;
	}

	public void setSaleaddr(String saleaddr) {
		this.saleaddr = saleaddr;
	}

	public BigDecimal getRegcapital() {
		return this.regcapital;
	}

	public void setRegcapital(BigDecimal regcapital) {
		this.regcapital = regcapital;
	}

	public String getCorptype() {
		return this.corptype;
	}

	public void setCorptype(String corptype) {
		this.corptype = corptype;
	}

	public String getBusiscope() {
		return this.busiscope;
	}

	public void setBusiscope(String busiscope) {
		this.busiscope = busiscope;
	}

	public String getDefStr1() {
		return this.defStr1;
	}

	public void setDefStr1(String defStr1) {
		this.defStr1 = defStr1;
	}

	public String getDefStr2() {
		return this.defStr2;
	}

	public void setDefStr2(String defStr2) {
		this.defStr2 = defStr2;
	}

	public String getDefStr3() {
		return this.defStr3;
	}

	public void setDefStr3(String defStr3) {
		this.defStr3 = defStr3;
	}

	public String getDefStr4() {
		return this.defStr4;
	}

	public void setDefStr4(String defStr4) {
		this.defStr4 = defStr4;
	}

	public String getDefStr5() {
		return this.defStr5;
	}

	public void setDefStr5(String defStr5) {
		this.defStr5 = defStr5;
	}

	public String getDefStr6() {
		return this.defStr6;
	}

	public void setDefStr6(String defStr6) {
		this.defStr6 = defStr6;
	}

	public String getDefStr7() {
		return this.defStr7;
	}

	public void setDefStr7(String defStr7) {
		this.defStr7 = defStr7;
	}

	public String getDefStr8() {
		return this.defStr8;
	}

	public void setDefStr8(String defStr8) {
		this.defStr8 = defStr8;
	}

	public BigDecimal getDefNum1() {
		return this.defNum1;
	}

	public void setDefNum1(BigDecimal defNum1) {
		this.defNum1 = defNum1;
	}

	public BigDecimal getDefNum2() {
		return this.defNum2;
	}

	public void setDefNum2(BigDecimal defNum2) {
		this.defNum2 = defNum2;
	}

	public String getPkOrg() {
		return this.pkOrg;
	}

	public void setPkOrg(String pkOrg) {
		this.pkOrg = pkOrg;
	}

	public String getPkGroup() {
		return this.pkGroup;
	}

	public void setPkGroup(String pkGroup) {
		this.pkGroup = pkGroup;
	}

	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	public Long getDr() {
		return this.dr;
	}

	public void setDr(Long dr) {
		this.dr = dr;
	}
	
	
}
