package cn.ffcs.uom.organization.model;

// Generated 2017-6-28 17:55:45 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import cn.ffcs.uom.common.dao.BaseDao;
import cn.ffcs.uom.common.util.ApplicationContextUtil;

/**
 * MdmContractId generated by hbm2java
 */
public class MdmContract implements Serializable {
	private static final long serialVersionUID = -5213396174105034970L;
	
	private Long id;
	private Long contractid;
	private String contractcode;
	private String signcode;
	private Boolean operatetype;
	private Boolean frameflag;
	private String partatype;
	private Boolean fundflag;
	private String contractname;
	private String contractfactbook;
	private BigDecimal tradesum;
	private BigDecimal currencytype;
	private String preContractcode;
	private String preContractname;
	private BigDecimal preTradesum;
	private BigDecimal tradesumChange;
	private String concode3class;
	private String partaname;
	private BigDecimal emergencydegree;
	private BigDecimal multsubject;
	private String frametype;
	private String frameareas;
	private String applyareaou;
	private String applydeptcode;
	private String applydept;
	private String applyuserid;
	private String applyusername;
	private String tel;
	private Byte status;
	private String poweranalyzeflag;
	private String pbasecontext;
	private String usecontext;
	private String subusecontext;
	private String creadate;
	private String finaldate;
	private String stampdate;
	private String signenddate;
	private String archivedate;
	private String signdate;
	private String enddate;
	private Boolean extendedterms;
	private Boolean extendedtype;
	private String extendedate;
	private String sourceSystem;
	private String stockmode;
	private String lastupdatetime;
	private Boolean ifictproject;
	private String ictprojectnum;
	private Long taxamount;
	private Boolean ifperiodic;
	private String perifrequency;
	private BigDecimal perieachamount;
	private Long manuscriptid;
	private Boolean ifoutsourccon;
	private String companyleader;
	private String companyleaderdesc;
	private String changedate;
	private Boolean iftradechange;
	private Boolean ifmaintenance;
	private String maintenyear;
	private String costtype;
	private String costtype2;
	private String taxitem;
	private Boolean taxableproperty;
	private String internalappitems;
	private Boolean renewcontractflag;
	private Boolean ifframeagree;
	private Boolean ifkeyconract;
	private Boolean ifupapproval;
	private String rentalpurposes;
	private String homeaddress;
	private BigDecimal rentalarea;
	private BigDecimal permeterrent;
	private String landhousenum;
	private String landhouseSrcId;
	private String contractcodeJt;
	private String stampuserid;
	private String signenduserid;
	private String archiveuserid;
	private String msgid;
	
	private String operatetypeName;
	private String frameflagName;
	private String fundflagName;

	/**
	 * 构造方法
	 */
	public MdmContract() {
		super();
	}

	/**
	 * 创建对象实例.
	 * 
	 * @return MdmContract
	 */
	public static MdmContract newInstance() {
		return new MdmContract();
	}

	/**
	 * 获取dao
	 * 
	 * @return
	 */
	public static BaseDao repository() {
		return (BaseDao) ApplicationContextUtil.getBean("baseDao");
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getContractid() {
		return this.contractid;
	}

	public void setContractid(Long contractid) {
		this.contractid = contractid;
	}

	public String getContractcode() {
		return this.contractcode;
	}

	public void setContractcode(String contractcode) {
		this.contractcode = contractcode;
	}

	public String getSigncode() {
		return this.signcode;
	}

	public void setSigncode(String signcode) {
		this.signcode = signcode;
	}

	public Boolean getOperatetype() {
		return this.operatetype;
	}

	public void setOperatetype(Boolean operatetype) {
		this.operatetype = operatetype;
	}

	public Boolean getFrameflag() {
		return this.frameflag;
	}

	public void setFrameflag(Boolean frameflag) {
		this.frameflag = frameflag;
	}

	public String getPartatype() {
		return this.partatype;
	}

	public void setPartatype(String partatype) {
		this.partatype = partatype;
	}

	public Boolean getFundflag() {
		return this.fundflag;
	}

	public void setFundflag(Boolean fundflag) {
		this.fundflag = fundflag;
	}

	public String getContractname() {
		return this.contractname;
	}

	public void setContractname(String contractname) {
		this.contractname = contractname;
	}

	public String getContractfactbook() {
		return this.contractfactbook;
	}

	public void setContractfactbook(String contractfactbook) {
		this.contractfactbook = contractfactbook;
	}

	public BigDecimal getTradesum() {
		return this.tradesum;
	}

	public void setTradesum(BigDecimal tradesum) {
		this.tradesum = tradesum;
	}

	public BigDecimal getCurrencytype() {
		return this.currencytype;
	}

	public void setCurrencytype(BigDecimal currencytype) {
		this.currencytype = currencytype;
	}

	public String getPreContractcode() {
		return this.preContractcode;
	}

	public void setPreContractcode(String preContractcode) {
		this.preContractcode = preContractcode;
	}

	public String getPreContractname() {
		return this.preContractname;
	}

	public void setPreContractname(String preContractname) {
		this.preContractname = preContractname;
	}

	public BigDecimal getPreTradesum() {
		return this.preTradesum;
	}

	public void setPreTradesum(BigDecimal preTradesum) {
		this.preTradesum = preTradesum;
	}

	public BigDecimal getTradesumChange() {
		return this.tradesumChange;
	}

	public void setTradesumChange(BigDecimal tradesumChange) {
		this.tradesumChange = tradesumChange;
	}

	public String getConcode3class() {
		return this.concode3class;
	}

	public void setConcode3class(String concode3class) {
		this.concode3class = concode3class;
	}

	public String getPartaname() {
		return this.partaname;
	}

	public void setPartaname(String partaname) {
		this.partaname = partaname;
	}

	public BigDecimal getEmergencydegree() {
		return this.emergencydegree;
	}

	public void setEmergencydegree(BigDecimal emergencydegree) {
		this.emergencydegree = emergencydegree;
	}

	public BigDecimal getMultsubject() {
		return this.multsubject;
	}

	public void setMultsubject(BigDecimal multsubject) {
		this.multsubject = multsubject;
	}

	public String getFrametype() {
		return this.frametype;
	}

	public void setFrametype(String frametype) {
		this.frametype = frametype;
	}

	public String getFrameareas() {
		return this.frameareas;
	}

	public void setFrameareas(String frameareas) {
		this.frameareas = frameareas;
	}

	public String getApplyareaou() {
		return this.applyareaou;
	}

	public void setApplyareaou(String applyareaou) {
		this.applyareaou = applyareaou;
	}

	public String getApplydeptcode() {
		return this.applydeptcode;
	}

	public void setApplydeptcode(String applydeptcode) {
		this.applydeptcode = applydeptcode;
	}

	public String getApplydept() {
		return this.applydept;
	}

	public void setApplydept(String applydept) {
		this.applydept = applydept;
	}

	public String getApplyuserid() {
		return this.applyuserid;
	}

	public void setApplyuserid(String applyuserid) {
		this.applyuserid = applyuserid;
	}

	public String getApplyusername() {
		return this.applyusername;
	}

	public void setApplyusername(String applyusername) {
		this.applyusername = applyusername;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getPoweranalyzeflag() {
		return this.poweranalyzeflag;
	}

	public void setPoweranalyzeflag(String poweranalyzeflag) {
		this.poweranalyzeflag = poweranalyzeflag;
	}

	public String getPbasecontext() {
		return this.pbasecontext;
	}

	public void setPbasecontext(String pbasecontext) {
		this.pbasecontext = pbasecontext;
	}

	public String getUsecontext() {
		return this.usecontext;
	}

	public void setUsecontext(String usecontext) {
		this.usecontext = usecontext;
	}

	public String getSubusecontext() {
		return this.subusecontext;
	}

	public void setSubusecontext(String subusecontext) {
		this.subusecontext = subusecontext;
	}

	public String getCreadate() {
		return this.creadate;
	}

	public void setCreadate(String creadate) {
		this.creadate = creadate;
	}

	public String getFinaldate() {
		return this.finaldate;
	}

	public void setFinaldate(String finaldate) {
		this.finaldate = finaldate;
	}

	public String getStampdate() {
		return this.stampdate;
	}

	public void setStampdate(String stampdate) {
		this.stampdate = stampdate;
	}

	public String getSignenddate() {
		return this.signenddate;
	}

	public void setSignenddate(String signenddate) {
		this.signenddate = signenddate;
	}

	public String getArchivedate() {
		return this.archivedate;
	}

	public void setArchivedate(String archivedate) {
		this.archivedate = archivedate;
	}

	public String getSigndate() {
		return this.signdate;
	}

	public void setSigndate(String signdate) {
		this.signdate = signdate;
	}

	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public Boolean getExtendedterms() {
		return this.extendedterms;
	}

	public void setExtendedterms(Boolean extendedterms) {
		this.extendedterms = extendedterms;
	}

	public Boolean getExtendedtype() {
		return this.extendedtype;
	}

	public void setExtendedtype(Boolean extendedtype) {
		this.extendedtype = extendedtype;
	}

	public String getExtendedate() {
		return this.extendedate;
	}

	public void setExtendedate(String extendedate) {
		this.extendedate = extendedate;
	}

	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	public String getStockmode() {
		return this.stockmode;
	}

	public void setStockmode(String stockmode) {
		this.stockmode = stockmode;
	}

	public String getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(String lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	public Boolean getIfictproject() {
		return this.ifictproject;
	}

	public void setIfictproject(Boolean ifictproject) {
		this.ifictproject = ifictproject;
	}

	public String getIctprojectnum() {
		return this.ictprojectnum;
	}

	public void setIctprojectnum(String ictprojectnum) {
		this.ictprojectnum = ictprojectnum;
	}

	public Long getTaxamount() {
		return this.taxamount;
	}

	public void setTaxamount(Long taxamount) {
		this.taxamount = taxamount;
	}

	public Boolean getIfperiodic() {
		return this.ifperiodic;
	}

	public void setIfperiodic(Boolean ifperiodic) {
		this.ifperiodic = ifperiodic;
	}

	public String getPerifrequency() {
		return this.perifrequency;
	}

	public void setPerifrequency(String perifrequency) {
		this.perifrequency = perifrequency;
	}

	public BigDecimal getPerieachamount() {
		return this.perieachamount;
	}

	public void setPerieachamount(BigDecimal perieachamount) {
		this.perieachamount = perieachamount;
	}

	public Long getManuscriptid() {
		return this.manuscriptid;
	}

	public void setManuscriptid(Long manuscriptid) {
		this.manuscriptid = manuscriptid;
	}

	public Boolean getIfoutsourccon() {
		return this.ifoutsourccon;
	}

	public void setIfoutsourccon(Boolean ifoutsourccon) {
		this.ifoutsourccon = ifoutsourccon;
	}

	public String getCompanyleader() {
		return this.companyleader;
	}

	public void setCompanyleader(String companyleader) {
		this.companyleader = companyleader;
	}

	public String getCompanyleaderdesc() {
		return this.companyleaderdesc;
	}

	public void setCompanyleaderdesc(String companyleaderdesc) {
		this.companyleaderdesc = companyleaderdesc;
	}

	public String getChangedate() {
		return this.changedate;
	}

	public void setChangedate(String changedate) {
		this.changedate = changedate;
	}

	public Boolean getIftradechange() {
		return this.iftradechange;
	}

	public void setIftradechange(Boolean iftradechange) {
		this.iftradechange = iftradechange;
	}

	public Boolean getIfmaintenance() {
		return this.ifmaintenance;
	}

	public void setIfmaintenance(Boolean ifmaintenance) {
		this.ifmaintenance = ifmaintenance;
	}

	public String getMaintenyear() {
		return this.maintenyear;
	}

	public void setMaintenyear(String maintenyear) {
		this.maintenyear = maintenyear;
	}

	public String getCosttype() {
		return this.costtype;
	}

	public void setCosttype(String costtype) {
		this.costtype = costtype;
	}

	public String getCosttype2() {
		return this.costtype2;
	}

	public void setCosttype2(String costtype2) {
		this.costtype2 = costtype2;
	}

	public String getTaxitem() {
		return this.taxitem;
	}

	public void setTaxitem(String taxitem) {
		this.taxitem = taxitem;
	}

	public Boolean getTaxableproperty() {
		return this.taxableproperty;
	}

	public void setTaxableproperty(Boolean taxableproperty) {
		this.taxableproperty = taxableproperty;
	}

	public String getInternalappitems() {
		return this.internalappitems;
	}

	public void setInternalappitems(String internalappitems) {
		this.internalappitems = internalappitems;
	}

	public Boolean getRenewcontractflag() {
		return this.renewcontractflag;
	}

	public void setRenewcontractflag(Boolean renewcontractflag) {
		this.renewcontractflag = renewcontractflag;
	}

	public Boolean getIfframeagree() {
		return this.ifframeagree;
	}

	public void setIfframeagree(Boolean ifframeagree) {
		this.ifframeagree = ifframeagree;
	}

	public Boolean getIfkeyconract() {
		return this.ifkeyconract;
	}

	public void setIfkeyconract(Boolean ifkeyconract) {
		this.ifkeyconract = ifkeyconract;
	}

	public Boolean getIfupapproval() {
		return this.ifupapproval;
	}

	public void setIfupapproval(Boolean ifupapproval) {
		this.ifupapproval = ifupapproval;
	}

	public String getRentalpurposes() {
		return this.rentalpurposes;
	}

	public void setRentalpurposes(String rentalpurposes) {
		this.rentalpurposes = rentalpurposes;
	}

	public String getHomeaddress() {
		return this.homeaddress;
	}

	public void setHomeaddress(String homeaddress) {
		this.homeaddress = homeaddress;
	}

	public BigDecimal getRentalarea() {
		return this.rentalarea;
	}

	public void setRentalarea(BigDecimal rentalarea) {
		this.rentalarea = rentalarea;
	}

	public BigDecimal getPermeterrent() {
		return this.permeterrent;
	}

	public void setPermeterrent(BigDecimal permeterrent) {
		this.permeterrent = permeterrent;
	}

	public String getLandhousenum() {
		return this.landhousenum;
	}

	public void setLandhousenum(String landhousenum) {
		this.landhousenum = landhousenum;
	}

	public String getLandhouseSrcId() {
		return this.landhouseSrcId;
	}

	public void setLandhouseSrcId(String landhouseSrcId) {
		this.landhouseSrcId = landhouseSrcId;
	}

	public String getContractcodeJt() {
		return this.contractcodeJt;
	}

	public void setContractcodeJt(String contractcodeJt) {
		this.contractcodeJt = contractcodeJt;
	}

	public String getStampuserid() {
		return this.stampuserid;
	}

	public void setStampuserid(String stampuserid) {
		this.stampuserid = stampuserid;
	}

	public String getSignenduserid() {
		return this.signenduserid;
	}

	public void setSignenduserid(String signenduserid) {
		this.signenduserid = signenduserid;
	}

	public String getArchiveuserid() {
		return this.archiveuserid;
	}

	public void setArchiveuserid(String archiveuserid) {
		this.archiveuserid = archiveuserid;
	}

	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	/**
	 * @return the operatetypeName
	 */
	public String getOperatetypeName() {
		return operatetypeName;
	}

	/**
	 * @param operatetypeName the operatetypeName to set
	 */
	public void setOperatetypeName(String operatetypeName) {
		this.operatetypeName = operatetypeName;
	}

	/**
	 * @return the frameflagName
	 */
	public String getFrameflagName() {
		return frameflagName;
	}

	/**
	 * @param frameflagName the frameflagName to set
	 */
	public void setFrameflagName(String frameflagName) {
		this.frameflagName = frameflagName;
	}

	/**
	 * @return the fundflagName
	 */
	public String getFundflagName() {
		return fundflagName;
	}

	/**
	 * @param fundflagName the fundflagName to set
	 */
	public void setFundflagName(String fundflagName) {
		this.fundflagName = fundflagName;
	}

}
