package cn.ffcs.uom.organization.model;

import java.io.Serializable;

import cn.ffcs.uom.common.dao.BaseDao;
import cn.ffcs.uom.common.util.ApplicationContextUtil;

// Generated 2017-7-5 9:38:06 by Hibernate Tools 3.4.0.CR1

/**
 * MdProfitcenter generated by hbm2java
 */
public class MdProfitcenter implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4474294328180295582L;
	
	private String prctr;
	private String kokrs;
	private String datab;
	private String datbi;
	private String ktext;
	private String ltext;
	private String verak;
	private String abtei;
	private String khinr;
	private String bukrs;
	private String status;
	private String remark1;
	private String remark2;
	private String remark3;
	private String remark4;
	private String remark5;
	private String remark6;
	private String remark7;
	private String remark8;
	private String remark9;
	private String remark10;
	private String msgid;

	/**
	 * 构造方法
	 */
	public MdProfitcenter() {
		super();
	}

	/**
	 * 创建对象实例.
	 * 
	 * @return MdProfitcenter
	 */
	public static MdProfitcenter newInstance() {
		return new MdProfitcenter();
	}

	/**
	 * 获取dao
	 * 
	 * @return
	 */
	public static BaseDao repository() {
		return (BaseDao) ApplicationContextUtil.getBean("baseDao");
	}

	public String getPrctr() {
		return this.prctr;
	}

	public void setPrctr(String prctr) {
		this.prctr = prctr;
	}

	public String getKokrs() {
		return this.kokrs;
	}

	public void setKokrs(String kokrs) {
		this.kokrs = kokrs;
	}

	public String getDatab() {
		return this.datab;
	}

	public void setDatab(String datab) {
		this.datab = datab;
	}

	public String getDatbi() {
		return this.datbi;
	}

	public void setDatbi(String datbi) {
		this.datbi = datbi;
	}

	public String getKtext() {
		return this.ktext;
	}

	public void setKtext(String ktext) {
		this.ktext = ktext;
	}

	public String getLtext() {
		return this.ltext;
	}

	public void setLtext(String ltext) {
		this.ltext = ltext;
	}

	public String getVerak() {
		return this.verak;
	}

	public void setVerak(String verak) {
		this.verak = verak;
	}

	public String getAbtei() {
		return this.abtei;
	}

	public void setAbtei(String abtei) {
		this.abtei = abtei;
	}

	public String getKhinr() {
		return this.khinr;
	}

	public void setKhinr(String khinr) {
		this.khinr = khinr;
	}

	public String getBukrs() {
		return this.bukrs;
	}

	public void setBukrs(String bukrs) {
		this.bukrs = bukrs;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark1() {
		return this.remark1;
	}

	public void setRemark1(String remark1) {
		this.remark1 = remark1;
	}

	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	public String getRemark3() {
		return this.remark3;
	}

	public void setRemark3(String remark3) {
		this.remark3 = remark3;
	}

	public String getRemark4() {
		return this.remark4;
	}

	public void setRemark4(String remark4) {
		this.remark4 = remark4;
	}

	public String getRemark5() {
		return this.remark5;
	}

	public void setRemark5(String remark5) {
		this.remark5 = remark5;
	}

	public String getRemark6() {
		return this.remark6;
	}

	public void setRemark6(String remark6) {
		this.remark6 = remark6;
	}

	public String getRemark7() {
		return this.remark7;
	}

	public void setRemark7(String remark7) {
		this.remark7 = remark7;
	}

	public String getRemark8() {
		return this.remark8;
	}

	public void setRemark8(String remark8) {
		this.remark8 = remark8;
	}

	public String getRemark9() {
		return this.remark9;
	}

	public void setRemark9(String remark9) {
		this.remark9 = remark9;
	}

	public String getRemark10() {
		return this.remark10;
	}

	public void setRemark10(String remark10) {
		this.remark10 = remark10;
	}

	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

}
